### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/facebook-poster#1]
Let me know when you're done writing tests and code. I'll do a quick review and setup Packagist and other services

**Comment by ahmedash95** [comment]
Dear @freekmurze, I am ready for the review , waiting your feedback :)

**Comment by freekmurze** [comment]
I'll take care of this in the next few days.

**Comment by freekmurze** [comment]
I've made PR #2 for you to review and pull

**Comment by freekmurze** [comment]
Fyi: In order to register the package on packagist I've made some modifications to the `composer.json` file on the master branch.
