### ISSUE TITLE
The Response content must be a string or object

### ISSUE THREAD

**Issue by Sjoerd** [laravel-notification-channels/facebook-poster#12]
Hi,
I'm trying to post something to my facebook page, but it doesn't work.
code:
```
public function post() {
  return new FacebookPosterPost('Laravel notifications are awesome!');
}
```

Error:
`The Response content must be a string or object implementing __toString(), "object" given.`

**Comment by ahmedash95** [comment]
sorry for delay, Could you please provide more info about laravel version ?

**Comment by Sjoerd** [comment]
I'm using the latest laravel version. (laravel 5.5.22)

**Comment by ahmedash95** [comment]
Hello again , 

I installed a fresh laravel app and setup my package following instructions in `ReadMe.md` file
specially this [part](https://github.com/laravel-notification-channels/facebook-poster#setting-up-the-facebook-poster-service) and It works fine with me with no errors 

I think you did something wrong with the implementation could you tell me which file contains your method `post` ?

**Comment by ahmedash95** [comment]
@Sjoerrdd Any updates ?

**Comment by SyafiqTM** [comment]
Hi @ahmedash95, i get the same error as Sjoerrdd when trying to pass from controller with FacebookPosterPost.

**Comment by SyafiqTM** [comment]
When trying to notify with $model->notify(new NewsWasPublished());

it returns with response : 
(#200) Requires either publish_actions permission, or manage_pages and publish_pages as an admin with sufficient administrative permission

even tho i was an administrator of the page

**Comment by SyafiqTM** [comment]
Im using ‘Get User Access Token’ and getting 'publish_pages’ and ‘manage_pages’ permissions are ticked referring on this [article ](https://adamboother.com/blog/automatically-posting-to-a-facebook-page-using-the-facebook-sdk-v5-for-php-facebook-api/)to solve the problem. And the rest of your instructions are working fine

**Comment by ahmedash95** [comment]
Hello @SyafiqTM 

did you check this [installation part](https://github.com/laravel-notification-channels/facebook-poster#setting-up-the-facebook-poster-service) .. please make sure you did it correctly and if you can share the [AccessToken debugger](https://developers.facebook.com/tools/debug/accesstoken) output

**Comment by ahmedash95** [comment]
@SyafiqTM any updates ?

**Comment by SyafiqTM** [comment]
hi @ahmedash95. yes, i can post my news on my facebook page perfectly fine 👌. Currently working on facebook OAuth to pass user token everytime they login. Thankyou very much

**Comment by ahmedash95** [comment]
My Pleasure Friend @SyafiqTM

**Comment by Karunesh-Vadaliya** [comment]
Hello everyone,
please help me to solve below error.

The Response content must be a string or object implementing __toString(), "object" given

getting reference from, https://laravel-excel.maatwebsite.nl/

in my controller Code:
use App\Exports\productExport;
use App\Imports\productImport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Controller;

public function import_products(Request $request) {
               return Excel::import(new productImport, $request->file);
}

**Comment by ahmedash95** [comment]
@Karunesh-Vadaliya I think your issue doesn't belong to this library, you should post your issue to https://github.com/Maatwebsite/Laravel-Excel/issues
