### ISSUE TITLE
Laravel 5.6

### ISSUE THREAD

**Issue by LucaRed** [laravel-notification-channels/facebook-poster#14]
Hi, I see that you added support for Laravel 5.6 in commit 236ce1b8518285b6f706ace3847542df029090a1.

Could you publish a new package release?

Thank you.

**Comment by ahmedash95** [comment]
Done [Supoort Laravel 5.6](https://github.com/laravel-notification-channels/facebook-poster/releases/tag/1.2.0) , and Thanks for mentioning that
