### ISSUE TITLE
Laravel 5.7 support

### ISSUE THREAD

**Issue by evilprogrammerng** [laravel-notification-channels/facebook-poster#16]
can't add or update from composer..
Please add 5.7 support.

Thank you.

**Comment by trondhuso** [comment]
I can confirm this wish.

**Comment by ahmedash95** [comment]
I will work on that tomorrow

**Comment by evilprogrammerng** [comment]
We will be expecting the update.
Thanks so much.

**Comment by ahmedash95** [comment]
Sorry guys for the delay, the internet at where I'm is very bad, currently, you can require dev-master until packagist read the last release which is `1.3.0`

```
composer require laravel-notification-channels/facebook-poster:dev-master
```
