### ISSUE TITLE
Posts not getting reached on facebook page

### ISSUE THREAD

**Issue by qaism** [laravel-notification-channels/facebook-poster#21]
when the post is finally published on the page, it didn't get reached at all.

**Comment by muhammedjailam** [comment]
Same issue here! Page admins can view the posts. But other users cant. I have also done business domain verification and associated the page to it. Any clues?

**Comment by atymic** [comment]
Can you show a screenshot of the post permissions?

**Comment by ahmedash95** [comment]
Hey @qaism @muhammedjailam , do you still have the issue?
