### ISSUE TITLE
The Response content must be a string or object implementing __toString(), "object" given

### ISSUE THREAD

**Issue by Karunesh-Vadaliya** [laravel-notification-channels/facebook-poster#22]
Hello Everyone,
please help me to solve issue.

Laravel version = 5.7.19

I getting error wen import Excel.

I have controller like, demoController and code show below,

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Hash;
use Session;
use File;
use Illuminate\Support\Facades\Mail;

use App\Exports\productExport;
use App\Imports\productImport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Controller;

class restaurantAdminController extends Controller {
            public function import_products(Request $request) {
                       return Excel::import(new productImport, $request->file); // not working. give error like,The Response content must be a string or object implementing __toString(), "object" given.
            }

    public function export_products(Request $request) {
        $data = $request->all();
        return Excel::download(new productExport, 'export_products.xls');//working fine
    }
}

Thanking You.

![Error-of-import-excel](https://user-images.githubusercontent.com/46314055/50585207-e669f680-0e99-11e9-8a3b-de3110180413.png)

**Comment by atymic** [comment]
Are you still having this issue?

**Comment by atymic** [comment]
Closing as inactive, if you are still having the issue let me know and i'll re-open.
