### ISSUE TITLE
publish_to_groups permission with user token

### ISSUE THREAD

**Issue by itwaree** [laravel-notification-channels/facebook-poster#26]
i am getting error ==>
(#200) If posting to a group, requires app being installed in the group, and \ either publish_to_groups permission with user token, or both manage_pages \ and publish_pages permission with page token; If posting to a page, \ requires both manage_pages and publish_pages as an admin with \ sufficient administrative permission

**Comment by nasirkhan** [comment]
Faced the same issue. 

I think the owner has abandoned this project. Sad.

**Comment by atymic** [comment]
Hi @nasirkhan 

I'm helping out with the notification channels now and will happily accept a PR to fix this :)

**Comment by nehasharma1997** [comment]
anybody have solve this issue ?

**Comment by dwightwatson** [comment]
Yes - you need to get a token with the required permissions. You can only post to groups that are owned by your app, and you also need to go through Facebook's review process in order to get access to the permissions. 

This used to be a lot easier before Facebook introduced the manual review process, but there is no other way around it.

**Comment by enricobono** [comment]
I'm facing the same issue while trying to post to a Facebook page.
I created the app, added the permission, switched the app to "active".
But still getting the same error.
Any clue?

**Comment by DEADSEC-SECURITY** [comment]
> I'm facing the same issue while trying to post to a Facebook page. I created the app, added the permission, switched the app to "active". But still getting the same error. Any clue?

Is your app verified by facebook?

**Comment by LightCannon** [comment]
Is there any update on this issue?
I was trying to post on groups which I'm not admin in, on behalf of my account, and I'm getting this.
