### ISSUE TITLE
Endpoints out of date

### ISSUE THREAD

**Issue by stevenhardy-digital** [laravel-notification-channels/facebook-poster#27]
Hello,
I have just installed this package on my laravel build, however the endpoints for posting are out of date and need updating:

`(#200) This endpoint is deprecated since the required permission publish_actions is deprecated`

This is using the below function:
```
  public function toFacebookPoster($image)
    {
        return (new FacebookPosterPost($image->description))->withImage(asset('albums/' . $image->album_id . '/' . $image->image));
    }
```

Please can you update them or tell me how to?

**Comment by ahmedash95** [comment]
Hello @medicsteven , sorry for the delay I will update them soon.

**Comment by mamulazmi** [comment]
any update ? @ahmedash95

**Comment by wassim** [comment]
@ahmedash95 any eta on this?

**Comment by atymic** [comment]
Hi,
do you know what the correct new endpoint is?

**Comment by atymic** [comment]
cc @dwightwatson 
Did you get this error when testing?

**Comment by stevenhardy-digital** [comment]
> Hi,
> do you know what the correct new endpoint is?

Here is a list of the end points. https://developers.facebook.com/docs/graph-api/reference

To be honest, I have not worked on my project that was going to use this in a little while. It maybe worth going through and updating them all.

**Comment by dwightwatson** [comment]
I'm sorry - I don't recall seeing the email notification from being tagged here. I'm using this package in product now without issue. I'm going to close this issue and will revisit if someone opens a new one.

**Comment by stevenhardy-digital** [comment]
Hello @dwightwatson 
I can confirm that this is all working as expected! Thank you for your help with this. This morning i managed to finish my project using this. Now the fun of trying to get Facebook to approve it!

Thanks again for your help
