### ISSUE TITLE
Permision errro

### ISSUE THREAD

**Issue by nohumans** [laravel-notification-channels/facebook-poster#3]
Don't publish

> FacebookResponseException in FacebookResponseException.php line 126:
> (#200) Requires extended permission: publish_actions

Thanxx

**Comment by ahmedash95** [comment]
Thanks for reporting this issue .. could you please check if your token has a publish_actions permission .. check this on readme

To create a long time access token for your fan page, open the [Graph Api Explorer](https://developers.facebook.com/tools/explorer/) on the right body heading, select your app then click on the get token button and select **Get Page Access Token** then select your page and click on the same button again and select **Request publish_pages** - this will allow app to publish posts to yourpage with your account authorization, after this add access_token parameter into the query string ```me?fields=id,name,access_token``` then submit and copy the access token and open this [Facebook Debugger Tool](https://developers.facebook.com/tools/debug/accesstoken) and paste your token then click on the Extend Access Token and take the long time expire token value to your env FACEBOOK_ACCESS_TOKEN.

**Comment by nohumans** [comment]
Hi!
Thanks , I extend time token with manage_pages, publish_pages, public_profile, 
I do not know how to obtain :  publish_actions , Facebook is dark and confusing...for me.

Thanxx

**Comment by ahmedash95** [comment]
@nohumans  I mean publish_pages not public actions .. sorry for that :).
happy to help .. please don't forget that you have to renew your token after 2 months .. cause Facebook time token extends for just 2 months ... coming release token will renew itself.
