### ISSUE TITLE
Facebook API Version

### ISSUE THREAD

**Issue by RicLeP** [laravel-notification-channels/facebook-poster#37]
Hi,

It looks like the Facebook PHP Graph SDK used by this package defaults to the Facebook Graph API version 2.10 which is being deprecated in under a month. Does this package user a later version? I couldn’t see where it was set, but Facebook’s package should allow setting it.

Thanks.

**Comment by dwightwatson** [comment]
Looks like it's actually the Facebook PHP SDK that defaults to 2.1.0: https://github.com/facebook/php-graph-sdk/blob/5.x/src/Facebook/Facebook.php#L61 and there is also some discussion about it: https://github.com/facebook/php-graph-sdk/issues/1157

We could expose an option to allow customising this I'd like to avoid that - Facebook should fix this up under the hood. If you really wanted to get around this you could override the service provider to customise the API version used.

Let's keep an eye and see if Facebook make any movement on this.
