### ISSUE TITLE
FACEBOOK_APP_ID missing ???

### ISSUE THREAD

**Issue by dgillier** [laravel-notification-channels/facebook-poster#42]
Hello I'm having the following error :
_Facebook\Exceptions\FacebookSDKException
Required "app_id" key not supplied in config and could not find fallback environment variable "FACEBOOK_APP_ID"_

I 'm having this into my .env file (fakes id & token):
```
FACEBOOK_APP_ID=YYYYYYYYY
FACEBOOK_APP_SECRET=ZZZZZZZZZ
FACEBOOK_ACCESS_TOKEN=TTTTTTTTTT
```

And I add this into services.php:
```
    'facebook_poster' => [
        'app_id' => env('FACEBOOK_APP_ID'),
        'app_secret' => env('FACEBOOK_APP_SECRET'),
        'access_token' => env('FACEBOOK_ACCESS_TOKEN'),
    ],
```
I'm using Laravel 7.1 and running with Homestead.
Any idea ? Thanks, Denis

**Comment by dwightwatson** [comment]
Have you cached your config?

Could you please dump `config('services.facebook_poster')` and ensure the right credentials are there?

**Comment by dgillier** [comment]
Thanks for your reply !

php artisan tinker
Psy Shell v0.10.3 (PHP 7.4.4 — cli) by Justin Hileman
>>> app('config')->get('services');
=> [
     "mailgun" => [
       "domain" => null,
       "secret" => null,
       "endpoint" => "api.mailgun.net",
     ],
     "postmark" => [
       "token" => null,
     ],
     "ses" => [
       "key" => "",
       "secret" => "",
       "region" => "us-east-1",
     ],
     "facebook_poster" => [
       "app_id" => “AAAAAAAAA",
       "app_secret" => “YYYYYY",
       "access_token" => “ZZZZZZZZ",
     ],
   ]
>>>
