### ISSUE TITLE
Linebreak in message

### ISSUE THREAD

**Issue by boutzamat** [laravel-notification-channels/facebook-poster#45]
Is it possible to send multiline messages to Facebook?
When i post a wysiwyg field as the notification, Facebook simply renders all the HTML tags.

So far i tried everything in this thread: https://stackoverflow.com/questions/7530999/facebook-graph-api-post-to-wall-doesnt-accept-new-line/13954640

**Comment by dwightwatson** [comment]
Not sure, sorry. Happy to look at PRs that assist.
