### ISSUE TITLE
withImage() and withVideo() removed

### ISSUE THREAD

**Issue by carnevalli** [laravel-notification-channels/facebook-poster#56]
Hi,

I noticed that withImage() and withVideo() methods were removed in commit [e3e46d6](https://github.com/laravel-notification-channels/facebook-poster/commit/e3e46d627f76fc7f1be8663e62bf1a2acb41e8af#diff-e002e22c1efc9cd01185f7b0ac0e410016863f2e1175306ece358022b0e5b068)

Are there any other alternatives to attach image or video to a post?

Thanks,

**Comment by amitbk** [comment]
I have implemented image posting on Facebook.
How can I contribute here to add the Facebook image posting feature?

**Comment by dwightwatson** [comment]
Happy to accept PRs.
