### ISSUE TITLE
Calling Wrong Access Token?

### ISSUE THREAD

**Issue by haleyngonadi** [laravel-notification-channels/facebook-poster#58]
Hi There,

I've updated my access token as the last open expired but FacebookPosterPost is still calling the older access token. I've cleared all my caches over and over again. I'm not sure what else to do?

```
Client error: `POST https://graph.facebook.com/v9.0/ID/feed?access_token=Token` resulted in a `403 Forbidden` response:
{"error":{"message":"(#200) If posting to a group, requires app being installed in the group, and \\\n          either p (truncated...)

```

The new access token has the right permissions, if only it would let me change it.

**Comment by dwightwatson** [comment]
Hoping that you were able to overcome this but please re-open if you're still having issues.
