### ISSUE TITLE
Method notify does not exist.

### ISSUE THREAD

**Issue by shinokada** [laravel-notification-channels/facebook-poster#6]
I am trying to post on Facebook and Twitter when creating an article if a radio box `facebook` and `twitter` is ticked.

I also have to get app_id etc from DB since there are 10 centers. And all centers have different facebook accounts.

In ArticleController

    use App\Notifications\FacebookPublished;
    use App\Notifications\TwitterPublished;

    ...
    ...
    public function store(StoreRequest $request)
    {
        $center = Center::where('id', $request->center_id)->first();
        //dd($request->title); // shows title 
        if($request->input('facebook'))
        {
            config(['app_id' => $center->facebook_app_id]); 
            config(['app_secret' => $center->facebook_app_secret]); 
            config(['access_token' => $center->facebook_access_token]); 
            // using $request
            $request->notify(new FacebookPublished());
        }
        if($request->input('twitter'))
        {
            config(['consumer_key' => $center->twitter_consumer_key]);
            config(['consumer_secret' => $center->twitter_consumer_secret]);
            config(['acess_token' => $center->twitter_access_token]);
            config(['access_secret' => $center->twitter_access_secret]);
            $request->notify(new TwitterPublished());
        }
        ...
        ...
    }

In App/Notifications/FacebookPublished,

```
namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use NotificationChannels\FacebookPoster\FacebookPosterChannel;
use NotificationChannels\FacebookPoster\FacebookPosterPost;

class FacebookPublished extends Notification
{
    public function via($notifiable)
    {
        return [FacebookPosterChannel::class];
    }

    public function toFacebookPoster($notifiable) {
        return (new FacebookPosterPost($request->title .' '.$request->content))->withImage($request->thumb);
    }
}

```

Article model:

```
namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Backpack\NewsCRUD\app\Models\Article as OriginalArticleModel;

class Article extends OriginalArticleModel
{
    use Notifiable;

    protected $fillable = ['slug', 'title', 'content', 'center_id', 'image','thumb', 'status', 'lightbox_folder','category_id', 'featured', 'date'];

}

```

When I store, I get an error;

> BadMethodCallException in Macroable.php line 74: Method notify does not exist.

What am I doing wrong here?

**Comment by ahmedash95** [comment]
Hi @shinokada , could you please provide more details about laravel version ? also I don't think request class have a ``` notify ``` method. 

could you please view this article to make sure that you did every thing well 
https://mattstauffer.co/blog/the-new-notification-system-in-laravel-5-3

I'm waiting your response

**Comment by shinokada** [comment]
Laravel Framework 5.4.17

I browsed the article you mentioned while I was coding. I also read your Readme and [this article](https://laravel-news.com/send-tweets-laravel-notifications).

Now I first stored the request and get the last insert id and used it to find the post.

    ....
    ....
        // this get the post from DB 
        $post = Article::find($item->getKey()); 
        if($request->input('facebook'))
        {
            config(['app_id' => $center->facebook_app_id]); 
            config(['app_secret' => $center->facebook_app_secret]); 
            config(['access_token' => $center->facebook_access_token]); 
            $post->notify(new FacebookPublished());
        }
        if($request->input('twitter'))
        {
            config(['consumer_key' => $center->twitter_consumer_key]);
            config(['consumer_secret' => $center->twitter_consumer_secret]);
            config(['acess_token' => $center->twitter_access_token]);
            config(['access_secret' => $center->twitter_access_secret]);
            $post->notify(new TwitterPublished());
        }
    ....
    ....

Now I get the following error.

> FacebookSDKException in Facebook.php line 139: Required "app_id" key not supplied in config and could not find fallback environment variable "FACEBOOK_APP_ID"

I set config 'app_id' etc on run time. But it did not pick it up. Mmmm

**Comment by ahmedash95** [comment]
in Article class you used the ``` Notifiable ``` trait .. so I think you have to use it to fire the notification. you told me that you don't want to save the model if the radio ticked is selected, so let's assume you don't want to create the model but we cound do something like 

```php

$article = new Article;
$article->title = $request->get('title');
$article->content = $request->get('content');
$article->thumb = $request->get('thumb_path');

// Then

$article->notify(new FacebookPublished);
```
i didn't try this but I should work with you

**Comment by shinokada** [comment]
Thanks I will try it.

BTW, I found that I need to set config like this.

        if($request->input('facebook'))
        {
            config(['services.facebook_poster.app_id' => $center->facebook_app_id]); 
            config(['services.facebook_poster.app_secret' => $center->facebook_app_secret]); 
            config(['services.facebook_poster.access_token' => $center->facebook_access_token]); 
            $post->notify(new FacebookPublished());
        }
        if($request->input('twitter'))
        {
            config(['services.twitter.consumer_key' => $center->twitter_consumer_key]);
            config(['services.twitter.consumer_secret' => $center->twitter_consumer_secret]);
            config(['services.twitter.acess_token' => $center->twitter_access_token]);
            config(['services.twitter.access_secret' => $center->twitter_access_secret]);
            $post->notify(new TwitterPublished());
        }

**Comment by ahmedash95** [comment]
try this 
```
config(['services.facebook_poster.app_id',$center->facebook_app_id]);
config(['services.facebook_poster.app_secret' => $center->facebook_app_secret]); 
config(['services.facebook_poster.access_token' => $center->facebook_access_token]); 
```

**Comment by ahmedash95** [comment]
aha , I'm a little bit late .. but what's the situation now ?

**Comment by shinokada** [comment]
I get this error now.

> ErrorException in FacebookPublished.php line 26: Undefined variable: article


    public function toFacebookPoster($notifiable) {
        return (new FacebookPosterPost($article->title .' '.$article->content));
    }


I will add a constructor and let you know.
Thank you for your help so far.

**Comment by ahmedash95** [comment]
I think you should use ``` $notificable ``` object
```php
public function toFacebookPoster($notifiable) {
    return (new FacebookPosterPost($notifiable->title .' '.$notifiable->content));
}
```

**Comment by shinokada** [comment]
Thanks. `$noifiable` works.

I get the following error. 

> FacebookResponseException in FacebookResponseException.php line 106: Invalid OAuth access token.

**Comment by ahmedash95** [comment]
Okay , try to set access token like this 
```php
$token = $center->facebook_app_id.'|'.$center->facebook_app_secret;
config(['services.facebook_poster.access_token' => $token]); 
```

**Comment by shinokada** [comment]
Now this error.

> FacebookResponseException in FacebookResponseException.php line 131: An active access token must be used to query information about the current user.

**Comment by ahmedash95** [comment]
hmmm , Let me test this today and back to you , maybe today at 9 PM. it's 9 AM now.

The problem here is related to generate access_token using app creditiails. i will try to find a way for this.

**Comment by shinokada** [comment]
Thanks. I am looking forward to hearing from you.

**Comment by shinokada** [comment]
I put mistakenly client token to facebook_access_token.
I got App token from https://developers.facebook.com/tools/accesstoken/ and used it. 

Then I got this error.

> FacebookResponseException in FacebookResponseException.php line 131: An active access token must be used to query information about the current user.

**Comment by ahmedash95** [comment]
@shinokada Hi again , Sorry I wasn't able to be online yesterday at night , looks like you make a progress .. could you share the code again after your updates ?

**Comment by shinokada** [comment]
Twitter works so far.
In ArticleController,

        
        $item = $this->crud->create($request->except(['save_action', '_token', '_method']));
        $this->data['entry'] = $this->crud->entry = $item;
        $post = Article::find($item->getKey()); 
        /* $this->post = new Article; */
        /* $this->post->title = $request->get('title'); */
        /* $this->post->content = strip_tags($request->get('content')); */
        //$article->thumb = $request->get('thumb_path');

        if($request->input('facebook'))
        {
            config(['services.facebook_poster.app_id' => $center->facebook_app_id]); 
            config(['services.facebook_poster.app_secret' => $center->facebook_app_secret]); 
            /* $token = $center->facebook_app_id.'|'.$center->facebook_app_secret; */
            /* config(['services.facebook_poster.access_token' => $token]); */  
            config(['services.facebook_poster.access_token' => $center->facebook_access_token]); 
            //$this->article->notify(new FacebookPublished);
            $post->notify(new FacebookPublished());
        }
        if($request->input('twitter'))
        {
            //dd($center->twitter_access_secret);
            config(['services.twitter.consumer_key' => $center->twitter_consumer_key]);
            config(['services.twitter.consumer_secret' => $center->twitter_consumer_secret]);
            config(['services.twitter.access_token' => $center->twitter_access_token]);
            config(['services.twitter.access_secret' => $center->twitter_access_secret]);
            //$this->article->notify(new TwitterPublished);
            $post->notify(new TwitterPublished());
        }


In App/Notifications/FacebookPublished.php

```
namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use NotificationChannels\FacebookPoster\FacebookPosterChannel;
use NotificationChannels\FacebookPoster\FacebookPosterPost;

class FacebookPublished extends Notification
{ 
    public function via($notifiable)
    {
        return [FacebookPosterChannel::class];
    }

    public function toFacebookPoster($notifiable) {
        return (new FacebookPosterPost($notifiable->title .' '. strip_tags($notifiable->content)))->withImage($notifiable->thumb);
        //return (new FacebookPosterPost($notifiable->title .' '.$notifiable->content));
    }
}

```

I also check the validity of access token at https://developers.facebook.com/tools/accesstoken/

**Comment by ahmedash95** [comment]
Hi @shinokada, sorry for delay .. I did some tests and improve the code base of the repository,

don't forget to run ``` composer update ```

now if you wanna per user settings in your model use ``` routeNotificationForFacebookPoster ```

```php
// Example
public function routeNotificationForFacebookPoster()
{
    return [
	'app_id' => $center->facebook_app_id,
	'app_secret' => $center->facebook_app_secret,
	'default_access_token' => $center->facebook_app_id.'|'.$center->facebook_app_secret,
    ];
}
```

So the full example now is 

```
...
if($request->input('facebook'))
    {
       /** here article model is using routeNotificationForFacebookPoster method **/
        $post->notify(new FacebookPublished());
    }
```
But you have to know that your access token must authorize publish page if you want to post on facebook pages you need request publish_page permission for valid token ..

**Comment by shinokada** [comment]
@ahmedash95, Thanks for your reply.

Where am I supposed to add `routeNotificationForFacebookPoster()` ? In FacebookPublished?

**Comment by ahmedash95** [comment]
Use it on your model , supposed to be Article.php

**Comment by ahmedash95** [comment]
@shinokada any updates ?

**Comment by shinokada** [comment]
I am waiting from FB after requesting publish_page permission. I am not able to login my test FB account at the moment. I hope I can test it soon. There are a quite[ few things ](https://developers.facebook.com/docs/facebook-login/review/what-is-login-review/)I have to clear before the test. I am not sure if I can pass these for my test FB account.

**Comment by ahmedash95** [comment]
@shinokada any updates about this ?

**Comment by shinokada** [comment]
Sorry, I working on other parts and haven't got time to do it yet.

**Comment by ahmedash95** [comment]
I will close it for now .. but waiting any updates from your side :).

Thanks.
