### ISSUE TITLE
Graph API v9.0 Deprecation? 

### ISSUE THREAD

**Issue by haleyngonadi** [laravel-notification-channels/facebook-poster#60]
Hi, thank you for this awesome package. I just logged into my Facebook developer dashboard and there's a notice: Reminder: Graph API v9.0 will be deprecated on Feb 23, 2023. Please use the [API Upgrade Tool](https://developers.facebook.com/tools/api_versioning/) to understand how this might impact your app. For more details see the [changelog](https://developers.facebook.com/docs/apps/changelog)

```
 $this->guzzle->post("https://graph.facebook.com/v9.0/{$pageId}/feed?access_token={$accessToken}", [
            'form_params' => $post->getBody(),
        ]);
```

Any chance we can get this upped before then? TIA!

**Comment by dwightwatson** [comment]
`master` now points to v18. Not sure whether it's worth making this configurable or not.
